version: "3.8"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # supervisor
    supervisor:
        build:
            context: './docker/supervisor'
            dockerfile: supervisor.dockerfile
        container_name: supervisor
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        build:
            context: '.'
            dockerfile: nginx.dockerfile
        container_name: nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
            - ${SERVER_PORT_SSL:-443}:443
        volumes:
            - ./:/var/www
            - ./docker/nginx_prd:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:8.0.37
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

    letsencrypt-cloudflare:
        image: certbot/dns-cloudflare
        
        # Dry Run
        command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials NS4ZC3Y6MTJD0IXPIM4QJ3L8BCF-BRDYX7JZ0VQW2M --agree-tos -d dilsonlana.com.br --server https://acme-v02.api.letsencrypt.org/directory --dry-run
    
        # Issue certificate
        # command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /opt/cloudflare/credentials --agree-tos -d test.example.com --server https://acme-v02.api.letsencrypt.org/directory
        
        # Renew certificate
        # command: renew --non-interactive --no-self-upgrade --dns-cloudflare --dns-cloudflare-credentials /opt/cloudflare/credentials --agree-tos --server https://acme-v02.api.letsencrypt.org/directory
        
        volumes:
          - ./cloudflare:/opt/cloudflare
          - ./letsencrypt:/etc/letsencrypt
          - ./letsencrypt/log:/var/log/letsencrypt
networks:
    laravel:
        driver: bridge
