name: CI-CD

#on:
#  push:
#    branches: [hmg]
#  pull_request:
#    branches: [hmg]

jobs:
 build-controlei-hmg:
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Homologation
      uses: appleboy/ssh-action@master
      with: 
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_IP }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /www/wwwroot/controlei_hmg && sh server_deploy_hmg.sh'